# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('planet_number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('planet_name', models.CharField(max_length=30)),
                ('planet_mass', models.PositiveIntegerField(max_length=10)),
            ],
        ),
    ]
