# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='orbital_speed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Average orbital speed, km/s'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='planet_mass_to_earth',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Planet mass relative to an Earth'),
        ),
    ]
