# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planets',
            name='planet_mass',
        ),
        migrations.AddField(
            model_name='planets',
            name='planet_mass_to_earth',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=10),
        ),
    ]
