# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('discovery_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'moon',
                'verbose_name_plural': 'moons',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('discovery_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('planet_mass_to_earth', models.DecimalField(blank=True, decimal_places=4, max_digits=10, verbose_name='planet mass relative to an Earth')),
                ('orbital_speed', models.DecimalField(blank=True, decimal_places=3, max_digits=5, verbose_name='Average orbital speed, km/s')),
                ('moons_quantity', models.PositiveSmallIntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name': 'planet',
                'verbose_name_plural': 'planets',
                'ordering': ['number'],
            },
        ),
        migrations.DeleteModel(
            name='Planets',
        ),
        migrations.AddField(
            model_name='moon',
            name='planet_mother',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planets.Planet'),
        ),
    ]
