# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_auto_20171222_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moons', to='planets.Planet'),
        ),
    ]
