# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_auto_20171219_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='discovery_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='planet',
            name='discovery_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
