# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_auto_20171212_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planets',
            options={'ordering': ['planet_number'], 'verbose_name': 'planet', 'verbose_name_plural': 'planets'},
        ),
        migrations.AddField(
            model_name='planets',
            name='satellites',
            field=models.PositiveSmallIntegerField(blank=True, default=0, max_length=2),
        ),
    ]
