# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_auto_20171219_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moon',
            options={'verbose_name': 'moon', 'verbose_name_plural': 'moons'},
        ),
        migrations.AlterModelOptions(
            name='planet',
            options={'verbose_name': 'planet', 'verbose_name_plural': 'planets'},
        ),
        migrations.RemoveField(
            model_name='moon',
            name='discovery_date',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='discovery_date',
        ),
        migrations.AddField(
            model_name='moon',
            name='wiki',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='wiki',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='moon',
            name='image',
            field=models.ImageField(blank=True, height_field=250, upload_to='images/', width_field=250),
        ),
        migrations.AlterField(
            model_name='planet',
            name='image',
            field=models.ImageField(blank=True, height_field=250, upload_to='images/', width_field=250),
        ),
    ]
