# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0004_auto_20180307_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='moon',
            name='escape_velocity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Escape velocity, km/s'),
        ),
        migrations.AddField(
            model_name='moon',
            name='mean_radius_to_earth',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Planet radius relative to an Earth'),
        ),
        migrations.AddField(
            model_name='moon',
            name='orbital_period',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Orbital period, day'),
        ),
        migrations.AddField(
            model_name='moon',
            name='surface_gravity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Surface gravity, g'),
        ),
        migrations.AddField(
            model_name='moon',
            name='surface_pressure',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Surface pressure, bar'),
        ),
        migrations.AddField(
            model_name='moon',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='planets/images/'),
        ),
        migrations.AddField(
            model_name='planet',
            name='escape_velocity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Escape velocity, km/s'),
        ),
        migrations.AddField(
            model_name='planet',
            name='mean_radius_to_earth',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Planet radius relative to an Earth'),
        ),
        migrations.AddField(
            model_name='planet',
            name='orbital_period',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Orbital period, day'),
        ),
        migrations.AddField(
            model_name='planet',
            name='rotation_period',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Rotation period, day'),
        ),
        migrations.AddField(
            model_name='planet',
            name='semi_major_axis',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Semi major axis, AU'),
        ),
        migrations.AddField(
            model_name='planet',
            name='surface_gravity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, verbose_name='Surface gravity, g'),
        ),
        migrations.AddField(
            model_name='planet',
            name='surface_pressure',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Surface pressure, bar'),
        ),
        migrations.AddField(
            model_name='planet',
            name='symbol',
            field=models.ImageField(blank=True, null=True, upload_to='planets/images/'),
        ),
    ]
