# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0004_auto_20171213_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='planets',
            name='planet_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
