# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0005_auto_20171219_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='image',
            field=models.ImageField(blank=True, upload_to='planets/images/'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='image',
            field=models.ImageField(blank=True, upload_to='planets/images/'),
        ),
    ]
