# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0005_auto_20180316_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='mean_radius_to_earth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Planet radius relative to an Earth'),
        ),
        migrations.AlterField(
            model_name='moon',
            name='surface_gravity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Surface gravity, g'),
        ),
        migrations.AlterField(
            model_name='moon',
            name='surface_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Surface pressure, bar'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='mean_radius_to_earth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Planet radius relative to an Earth'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='orbital_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Average orbital speed, km/s'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='planet_mass_to_earth',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Planet mass relative to an Earth'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='semi_major_axis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Semi major axis, AU'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='surface_gravity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Surface gravity, g'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='surface_pressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Surface pressure, bar'),
        ),
    ]
