# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0006_auto_20180318_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moon',
            name='orbital_period',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='orbital_period',
            field=models.TextField(blank=True, default='days'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planet',
            name='rotation_period',
            field=models.TextField(blank=True),
        ),
    ]
