# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0007_auto_20171220_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moon',
            name='planet_mother',
        ),
        migrations.AddField(
            model_name='moon',
            name='planet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='planet_mother', to='planets.Planet'),
            preserve_default=False,
        ),
    ]
