# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0007_auto_20171213_1818'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moons',
            new_name='Moon',
        ),
        migrations.RenameModel(
            old_name='Planets',
            new_name='Planet',
        ),
    ]
