# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0007_auto_20180319_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moon',
            options={'ordering': ['number_m'], 'verbose_name': 'moon', 'verbose_name_plural': 'moons'},
        ),
        migrations.RenameField(
            model_name='moon',
            old_name='number',
            new_name='number_m',
        ),
    ]
